version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=true
    depends_on:
      - prometheus
      
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: "host"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem'
      - '--collector.diskstats'
      - '--collector.meminfo'
      - '--collector.cpu'
      - '--collector.netdev'
      - '--collector.loadavg'
      - '--collector.processes'
      - '--collector.uname'
      - '--collector.vmstat'
      - '--collector.systemd'
      - '--collector.netstat'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    restart: unless-stopped
    
  mac-disk-exporter:
    image: busybox
    container_name: mac-disk-exporter
    command: sh -c "while true; do df -h / | grep -v Filesystem | awk '{print \"mac_disk_total_bytes \"{2}; print \"mac_disk_used_bytes \"{3}; print \"mac_disk_avail_bytes \"{4}; print \"mac_disk_used_percent \"{5}}' > /tmp/metrics; sleep 60; done"
    volumes:
      - /:/host:ro
      - disk-metrics:/tmp
    restart: unless-stopped

volumes:
  grafana_data:
  disk-metrics: